stages: [test]

cypress_tests:
  stage: test
  image: cypress/browsers:node-22.19.0-chrome-139.0.7258.154-1-ff-142.0.1-edge-139.0.3405.125-1
  script:
    - npm ci
    - npx cypress run --browser chrome --headless