stages:
  - test

cypress_tests:
  stage: test
  image: cypress/base:22.19.0
  script:
    - npm ci
    - echo "DB_CONNECT=mongodb+srv://$MONGODB_ACCESS$MONGODB_HOST?retryWrites=true&w=majority&appName=Cluster0" > .env
    - npm run test:api
