stages:
  - test
  - perf

cypress_tests:
  stage: test
  image: cypress/base:22.19.0
  script:
    - npm ci
    - echo "DB_CONNECT=mongodb+srv://$MONGODB_ACCESS$MONGODB_HOST?retryWrites=true&w=majority&appName=Cluster0" > .env
    - npm run test:api

JMeter_perf:
  stage: perf
  image:
    name: alpine/jmeter:latest
    entrypoint: [""] 
  script:
    - apk add --no-cache nodejs npm
    - npm ci
    - echo "DB_CONNECT=mongodb+srv://$MONGODB_ACCESS$MONGODB_HOST?retryWrites=true&w=majority&appName=Cluster0" > .env
    - npm start &
    - jmeter -n -t tests/mytest.jmx -l out.jtl -e -o out -Jduration=120
  artifacts:
    when: always
    paths:
      - out